---
title: "Genetic Algorithm"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load_libraries}
library(tidyverse)
library(ggthemes)
library(gridExtra)
library(GGally)
library(tidymodels)
library(glmnet)
library(kernlab)
library(genalg)
library(here)

acc <- function(confusion_matrix) {
  sum(diag(confusion_matrix)) / sum(confusion_matrix)
}
select <- dplyr::select
```


```{r load_tr_data}


train <- read.csv(here("data", "training.csv"))
dim(train)
# names(train)

# To remove
train %>%
  filter(col1 < 1) %>%
  dim()
train <- train %>% filter(col1 >= 1)
```




```{r}
test <- read.csv(here("data", "testing.csv"))
dim(test)
# To remove
test %>%
  filter(col1 < 1) %>%
  dim()
test <- test %>% filter(col1 >= 1)
```

Convert to absorbance
```{r abs}
train[, 2:1061] <- log10(1 / train[, 2:1061])
test <- log10(1 / test)
```



## Split and scale training data

```{r}


set.seed(1979)

train <- train %>% mutate(Diet = as.factor(Diet))
tr <- initial_split(train, prop = .5, strata = Diet)
train_data <- training(tr)
test_data <- testing(tr)

mn <- apply(train_data %>% select(-Diet), 2, mean)
sd <- apply(train_data %>% select(-Diet), 2, sd)

train_data[, -c(1)] <- sweep(train_data[, -c(1)], 2, mn, "-")
train_data[, -c(1)] <- sweep(train_data[, -c(1)], 2, sd, "/")

test_data[, -c(1)] <- sweep(test_data[, -c(1)], 2, mn, "-")
test_data[, -c(1)] <- sweep(test_data[, -c(1)], 2, sd, "/")
```

# AC feature reduction


```{r}
unit <- (5010 - 925) / 1060
xx <- c(1592, 1720, 2996, 3698, 3818)
ac_region <- c(1:173, 206:537, 720:751)
```



## Marginal relevance




```{r MR}


library(BKPC)


margRelv <- marginalRelevance(train_data %>% select(-Diet), train_data$Diet)



mr <- as_tibble(cbind(1:1060, t(margRelv$score))) %>% rename(vars = V1, score = V2)
```


```{r}

reject1 <- c(174:205)
reject2 <- c(538:719)
reject3 <- c(751:1060)
c(
  173 + which(mr[reject1, 2] == max(mr[reject1, 2])),
  537 + which(mr[reject2, 2] == max(mr[reject2, 2])),
  750 + which(mr[reject3, 2] == max(mr[reject3, 2]))
)
ac_region_plus <- c(ac_region, 205, 556, 952)
```




```{r select_columns}

train_data <- train_data[, c(1, ac_region_plus + 1)]

test_data <- test_data[, c(1, ac_region_plus + 1)]


dim(train_data)
dim(test_data)
```


```{r MR2}

margRelv <- marginalRelevance(train_data %>% select(-Diet), train_data$Diet)

mr <- as_tibble(cbind(1:(ncol(train_data) - 1), t(margRelv$score))) %>% rename(vars = V1, score = V2)

mr %>%
  ggplot(aes(x = vars, y = score)) +
  geom_line() +
  geom_hline(yintercept = 0.002)


train_data <- train_data[, c(TRUE, mr$score > 0.002)]

test_data <- test_data[, c(TRUE, mr$score > 0.002)]

dim(train_data)
dim(test_data)
```


# GA




```{r cv, eval = TRUE}
set.seed(1979)
folds <- train_data %>% vfold_cv(v = 10, strata = Diet)

cv_data <- folds %>%
  mutate(
    train = map(splits, ~ training(.x)),
    validate = map(splits, ~ testing(.x))
  )
```

```{r eval = FALSE}

fit_lda_fun <- function(tr, te) {
  fit_lda <- MASS::lda(Diet ~ .,
    tr,
    prior = c(1, 1, 1) / 3
  )
  pred_lda <- fit_lda %>%
    predict(te)

  pred_lda <- pred_lda$class

  conf_lda <- table(te$Diet, pred_lda)
  acc_lda <- acc(conf_lda)
}





guts <- function(chromosome = c()) {
  th <- chromosome
  print(sum(th))
  if (sum(th) == 0) {
    print("no vars included")
    return(0)
  }
  tr_data <- cv_data$train %>% map(~ .x[, c(TRUE, th == 1)])
  te_data <- cv_data$validate %>% map(~ .x[, c(TRUE, th == 1)])
  accr_new_full <- tr_data %>% map2(te_data, ~ fit_lda_fun(.x, .y))
  accr <- accr_new_full %>%
    unlist() %>%
    mean()

  return(-(accr))
}
monitor <- function(obj) {}


woppa2 <- rbga.bin(size = (ncol(train_data) - 1),
                   mutationChance = 0.05, 
                   zeroToOneRatio = 5, 
                   evalFunc = guts, 
                   iters = 20, 
                   verbose = TRUE, 
                   monitorFunc = monitor)





theta.optimum2 <- woppa2$population[woppa2$evaluations == min(woppa2$evaluations), ]


# saveRDS(theta.optimum2, "theta3.Rds")
```
